### ISSUE TITLE
Proper use of semantic versioning in this orb

### ISSUE THREAD

**Issue by jamesbraza** [codecov/codecov-circleci-orb#100]
[Orb version 1.2.3](https://circleci.com/developer/orbs/orb/codecov/codecov?version=1.2.3) had the `token` parameter of type `string`.

[Orb version 1.2.4](https://circleci.com/developer/orbs/orb/codecov/codecov?version=1.2.4) (and 1.2.5), published last Friday on 7/16/2021, now has the `token` parameter as type `env_var_name`.

In my mind, this is a non-backwards compatible breaking change, and thus should have been a major version bump (not a bugfix version bump).

According to https://circleci.com/docs/2.0/orbs-faq/#how-to-use-the-latest-version-of-an-orb, CircleCI uses semantic versioning for its orbs.  I had pinned the orb based on the major version of the uploader:

```yaml
orbs:
  # SEE: https://circleci.com/orbs/registry/orb/codecov/codecov
  codecov: codecov/codecov@1
```

Since last Friday, all of my repos using this orb need an update for the way the `token` is passed.  Just keep this in mind please.
