### ISSUE TITLE
Validate Codecov Uploader - gpgv: Can't check signature: No public key

### ISSUE THREAD

**Issue by vfn** [codecov/codecov-circleci-orb#159]
The codecov orb started failing recently on my CircleCI workflows. I was originally using v3.2.2 with no issues, until it started failing. I then changed to the latest v3.2.4, but the issue did not resolve.

```
#!/bin/sh -eo pipefail
source $BASH_ENV
echo "${CODECOV_PUBLIC_PGP_KEY}" | \
  gpg --no-default-keyring --keyring trustedkeys.gpg --import
# One-time step
sha_url="https://uploader.codecov.io"
sha_url="$sha_url/${version}/${os}"
sha_url="$sha_url/${filename}.SHA256SUM"
echo "Downloading ${sha_url}"
curl -Os $sha_url
curl -Os $sha_url".sig"
gpgv $filename.SHA256SUM.sig $filename.SHA256SUM
shasum -a 256 -c $filename.SHA256SUM || \
  sha256sum -c $filename.SHA256SUM

gpg: directory '/root/.gnupg' created
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key 806BB28AED779869: public key "Codecov Uploader (Codecov Uploader Verification Key) <security@codecov.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1
Downloading https://uploader.codecov.io/latest/alpine/codecov.SHA256SUM
gpgv: unknown type of key resource 'trustedkeys.kbx'
gpgv: keyblock resource '/root/.gnupg/trustedkeys.kbx': General error
gpgv: Signature made Thu Apr 20 16:45:41 2023 UTC
gpgv:                using RSA key 27034E7FDB850E0BBC2C62FF806BB28AED779869
gpgv: Can't check signature: No public key

Exited with code exit status 2
CircleCI received exit code 2
```
<img width="1036" alt="image" src="https://github.com/codecov/codecov-circleci-orb/assets/308592/5f132c89-29b6-464f-b160-0294b8cbe17f">

Is there anything I can do on my end to get this sorted?

**Comment by vfn** [comment]
@thomasrockhu-codecov I'm sorry, I'm not sure how to answer your question. What info would you like?

The error above is coming from the [validation step](https://github.com/codecov/codecov-circleci-orb/blob/3.2.4/src/scripts/validate.sh).

This is the job I have configured on my CircleCI config.yml file:
```YAML
version: 2.1

orbs:
  codecov: codecov/codecov@3.2.4

...

jobs:

...

  upload_coverage:
    docker:
      - image: alpine
    resource_class: small
    working_directory: /mnt/ramdisk # https://circleci.com/docs/2.0/executor-types/#ram-disks
    steps:
      - *attach_workspace

      - run:
          name: Install codecov uploader dependencies
          command: |
            set -exu
            apk add curl gnupg coreutils

      - codecov/upload:
          token: CODECOV_UPLOAD_TOKEN
          file: "/tmp/workspace/outputs/coverage_report/cobertura.xml"
          xtra_args: -v -R "/mnt/ramdisk"

...
```

**Comment by vfn** [comment]
Closing this issue as duplicate of https://github.com/codecov/codecov-circleci-orb/issues/157

The fix posted by @bonkey does work (https://github.com/codecov/codecov-circleci-orb/issues/157#issue-1692263650):

> Simple hack to fix it consist of mkdir ~/.gnupg before executing codecov/upload:

```yaml
      - run:
          name: Quick fix for GPG error in Codecov
          command: mkdir -p ~/.gnupg
      - codecov/upload
```
