### ISSUE TITLE
[Feature request] Support custom variable name in "upload_name" field

### ISSUE THREAD

**Issue by tniezurawski** [codecov/codecov-circleci-orb#230]
When not specified, `upload_name` uses `$CIRCLE_BUILD_NUM`, which [I found in the changelog](https://github.com/codecov/codecov-circleci-orb/blob/716e4e269d4d81382666a5b853771d7f8a14d14f/CHANGELOG.md?plain=1#L176). The docs suggest an empty string:

![Image](https://github.com/user-attachments/assets/b23daef0-2cd8-49c7-853e-42cb8083111c)

☝ this could be treated as a small "bug" in docs 😉 but I actually wanted to ask for a feature.

It would be nice to name uploaded reports per container. Unfortunately, CircleCI doesn't support environment variable interpolation in `yaml` so something like this:

```yml
upload_name: "container_${CIRCLE_NODE_INDEX}"
```

is going to result in the name as we see it:

![Image](https://github.com/user-attachments/assets/405ee74d-ec9a-4e1e-9408-1007a241319d)

But I'd be totally fine with preparing the variable name in a previous step, like this, and using it later:

```yml
- run:
    name: Set CODECOV_UPLOAD_NAME
    command: echo "export CODECOV_UPLOAD_NAME=container_${CIRCLE_NODE_INDEX}" >> $BASH_ENV
- codecov/upload:
    upload_name: "$CODECOV_UPLOAD_NAME"
```

or to be more explicit:

```diff
- upload_name: "$CODECOV_UPLOAD_NAME"
+ upload_name_var: "$CODECOV_UPLOAD_NAME"
```

With whatever priority `upload_name` vs `upload_name_var` should have in case they are used together.

What do you think?
