### ISSUE TITLE
[BUG] Broken on Alpine

### ISSUE THREAD

**Issue by chipshort** [codecov/codecov-circleci-orb#235]
**Describe the bug**

The orb doesn't work if it's run inside an Alpine Linux Docker image.

```
     _____          _
    / ____|        | |
   | |     ___   __| | ___  ___ _____   __
   | |    / _ \ / _` |/ _ \/ __/ _ \ \ / /
   | |___| (_) | (_| |  __/ (_| (_) \ V /
    \_____\___/ \__,_|\___|\___\___/ \_/
                            Wrapper-0.1.0
                                  
==> Bypassing validation...
/bin/sh: syntax error: unexpected "("

Exited with code exit status 2
```

**To Reproduce**

Use this job definition on the https://github.com/CosmWasm/cosmwasm repo.
```yml
  coverage:
    docker:
      - image: rust:1.84.1-alpine3.21
    environment:
      # Limit the number of parallel jobs to avoid OOM crashes during doc testing
      RUST_TEST_THREADS: 8
    resource_class: medium+
    steps:
      - checkout
      - run:
          name: Install necessary packages
          command: |
            apk update
            apk add mold clang curl coreutils llvm19-dev zlib-static clang19-static
      - run:
          name: Install grcov
          command: |
            rustup component add llvm-tools-preview
            cargo install grcov --locked
      - run:
          name: Install codecov uploader
          command: |
            #download Codecov CLI
            curl -Os https://cli.codecov.io/v10.1.0/alpine/codecov
            chmod +x codecov
            ./codecov --help
      - run:
          name: Run tests with coverage
          command: |
            mkdir -p reports
            cargo test -p cosmwasm-crypto --all-features

            grcov . -s packages/crypto --binary-path ./target/debug -t lcov -o ./reports/crypto.info
          environment:
            RUSTFLAGS: "-Clinker=clang -Clink-arg=-fuse-ld=/usr/bin/mold -Cinstrument-coverage"
            LLVM_PROFILE_FILE: "cosmwasm-%p-%m.profraw"
      - codecov/upload:
          binary: ./codecov
          files: reports/crypto.info
          disable_search: true
          flags: cosmwasm-crypto
```

**Regression**

This used to work with orb version 4.1.0

**Versions**

See the job definition.
Use the latest version of the orb:
```yml
orbs:
  codecov: codecov/codecov@5.2.1
```

**Commit and CI link**

https://github.com/CosmWasm/cosmwasm/pull/2391/commits/593199dc91078f1335b7ad0f959398563e36999d

**Additional context**

The problem seems very similar to this issue: https://github.com/codecov/codecov-circleci-orb/issues/8
