### ISSUE TITLE
Make the `file:` parameter optional, or support multiple files.

### ISSUE THREAD

**Issue by jfairley** [codecov/codecov-circleci-orb#6]
I've used the codecov-bash for quite a while in my CI jobs like follows:

```
bash <(curl -s https://codecov.io/bash) 
```

I love that CodeCov had created a CircleCI orb, but I'm not happy with the required `file` parameter.

Call me lazy, but I love the original functionality of the codecov script just finding the coverage file on its own. It's one less concern for me when configuring CI.

_Not to mention_ I have many projects which produce coverage reports in multiple formats. One such projects creates clover, junit, and lcov reports. I'm not sure whether any one is better than any other. I am currently arbitrarily choosing one of them. Would CodeCov prefer one of the others? I don't know.

I have also tried to solve this problem like: `file: "coverage/*"`, but only the first matching report is uploaded, rather than _all_ matching reports.

---

So my feature request could be any of the following:

1. The `file:` parameter is no longer required.
2. The `file:` parameter takes an array (or `files:` is introduced).
3. Functionality of `file:` taking a regex is improved upon.

**Comment by jfairley** [comment]
Oh another point... I have so far stayed away from my multi-module maven projects, which legitimately produce multiple reports. In the current environment, I would be forced to call the `upload` command multiple times:

```yaml
- codecov/upload:
    file: module-1/target/jacoco/jacoco.xml
- codecov/upload:
    file: module-2/target/jacoco/jacoco.xml
- codecov/upload:
    file: module-3/target/jacoco/jacoco.xml
- codecov/upload:
    file: module-4/submodule-1/target/jacoco/jacoco.xml
- codecov/upload:
    file: module-4/submodule-2/target/jacoco/jacoco.xml
- codecov/upload:
    file: module-4/submodule-3/target/jacoco/jacoco.xml
```


I actually have a project which has around 10 such modules. That's 10 uploads. 😦
