### ISSUE TITLE
Cannot find a definition for job named codecov/upload

### ISSUE THREAD

**Issue by brunoscopelliti** [codecov/codecov-circleci-orb#80]
Hello there,

I'm learning circleci.
I'm not sure I am doing something wrong, or there is something wrong with this orb.

Below is my circleci config file;
apparently it is invalid cause `Cannot find a definition for job named codecov/upload`.

```
version: 2.1

orbs:
  node: circleci/node@3.0.0
  codecov: codecov/codecov@1.1.4

workflows:
  unit-tests:
    jobs:
      - node/test:
          version: 15.9.0
      - codecov/upload:
          file: coverage/coverage-final.json
```

![image](https://user-images.githubusercontent.com/3489757/116795201-76082a00-aad3-11eb-86c5-bd9b5ab1146a.png)

Is there any problem with this configuration? (what?).

Thank you

**Comment by brunoscopelliti** [comment]
Ok, solved the problem:

```
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.5

jobs:
  unit-tests:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: npm install
      - run: npm test
      - codecov/upload:
          file: coverage/coverage-final.json

workflows:
  test:
    jobs:
      - unit-tests
```
