### ISSUE TITLE
1.1.5 shasum fails on macos executor

### ISSUE THREAD

**Issue by ahampe** [codecov/codecov-circleci-orb#83]
Excerpt of our circle config:
```
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.5

executors:
  env_executor:
    macos:
      xcode: "12.0.0"
```

Pipeline fails at "Validate codecov bash uploader" step:
```
#!/bin/bash --login -eo pipefail
VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
for i in 1 256 512
do
  shasum -a $i -c --ignore-missing <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM) ||
  shasum -a $i -c <(curl -s https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM)
done

Unknown option: ignore-missing
Type shasum -h for help
(23) Failed writing body
codecov: OK
shasum: env: 
env: FAILED open or read
shasum: WARNING: 1 listed file could not be read

Exited with code exit status 1
CircleCI received exit code 1
```
